# Generated by Django 3.0.3 on 2020-03-24 20:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to=settings.AUTH_USER_MODEL
                )),
                ('birthday', models.DateField(null=True, verbose_name='Дата рождения')),
                ('info', models.TextField(default='', verbose_name='Информация о пользователе')),
                ('bio', models.TextField(default='', verbose_name='Происхождение пользователя')),
                ('is_prime', models.BooleanField(default=False, verbose_name='Есть ли подписка')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
