# Generated by Django 3.0.3 on 2020-04-29 02:34

from django.db import migrations
from django.db import models
import profile_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True,
                                   upload_to=profile_page.models.Profile.path,
                                   verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100,
                                   null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100,
                                   null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True,
                                         related_name='_profile_friend_+',
                                         to='profile_page.Profile',
                                         verbose_name='Друзья'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True,
                                   verbose_name='Происхождение пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=models.TextField(blank=True, default='', null=True,
                                   verbose_name='Информация о пользователе'),
        ),
    ]
