# Generated by Django 3.0.3 on 2020-05-05 00:28

import aim.models
from django.db import migrations
from django.db import models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_page', '0002_auto_20200429_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100,
                                           verbose_name='Название')),
                ('info', models.TextField(blank=True, null=True,
                                          verbose_name='Описание')),
                ('picture', models.FileField(blank=True, null=True,
                                             upload_to=aim.models.Aim.path,
                                             verbose_name='Картинка')),
                ('rate', models.PositiveSmallIntegerField(
                    default=0,
                    verbose_name='Оценка'
                )),
                ('author', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='profile_page.Profile',
                    verbose_name='Автор цели'
                )),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цель',
            },
        ),
        migrations.CreateModel(
            name='UserAim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(
                    default=django.utils.timezone.now,
                    verbose_name='Дата создания')),
                ('completed', models.DateTimeField(
                    blank=True,
                    null=True,
                    verbose_name='Дата выполнения')),
                ('deadline', models.DateTimeField(
                    blank=True,
                    null=True,
                    verbose_name='Крайний срок'
                )),
                ('is_closed', models.BooleanField(default=False,
                                                  verbose_name='Закрыта')),
                ('regularity', models.PositiveSmallIntegerField(
                    blank=True,
                    choices=[(1, 'Каждый день'), (2, 'Каждую неделю'),
                             (3, 'Каждый месяц'), (4, 'Каждый год')],
                    null=True,
                    verbose_name='Регулярность'
                )),
                ('aim', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    to='aim.Aim',
                    verbose_name='Цель'
                )),
                ('profile', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='profile_page.Profile',
                    verbose_name='Пользователь'
                )),
            ],
        ),
    ]
