# Generated by Django 3.0.3 on 2020-05-05 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0002_auto_20200429_0534'),
        ('aim', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraim',
            options={'verbose_name': 'Цель пользователя', 'verbose_name_plural': 'Цели пользователей'},
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_page.Profile', verbose_name='Автор')),
                ('user_aim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.UserAim', verbose_name='Цель пользователя')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_page.Profile', verbose_name='Автор')),
                ('user_aim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.UserAim', verbose_name='Цель пользователя')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментрии',
            },
        ),
    ]
